### ISSUE TITLE
How to use downloaded log content?

### ISSUE THREAD

**Issue by TrongTheAlpaca** [MahjongRepository/phoenix-logs#1]
Heya, nice project!

I have a question when it comes to the log content.

I begun by executing `python main.py -a id -y 2019` which generates a db file `db/2019.db` with saved IDs.
Then, I executed `python main.py -a content -y 2019 -l 50 -t 3`.
From what I understood, this stores the downloaded log content into said .db file.

Was wondering how one can use the downloaded log content? I can see that the created db-file has content in the `log content` property. How do I actually use this content? 

@Nihisil, I assume you are the one I can ask?

**Comment by Nihisil** [comment]
Hi! File where logs stored is .sqlite file with compressed log content.

There is example how to get logs content from DB: https://github.com/MahjongRepository/tenhou-python-bot/blob/dev/project/statistics/db.py#L5

There is example how to separate log content on tags: https://github.com/MahjongRepository/tenhou-python-bot/blob/dev/project/statistics/log_parser.py#L6

Let me know if you have any questions.

**Comment by TrongTheAlpaca** [comment]
Hello again, thanks for fast response!

I followed your tips, and created this test code 
```python
    db_path = 'db/2019.db'

    num_logs = get_total_logs_count(db_path)
    print(num_logs)  # Prints: '216880'

    loaded_logs = load_logs_from_db(db_path, limit=1, offset=1)  # Not sure how LIMIT and OFFSET works here? Dates?
    print('Number of loaded logs:', len(loaded_logs))  # Prints '1' => I retrieved 1 log out of 216880 logs.

    for log in loaded_logs:

        parsed_log = LogParser().split_log_to_game_rounds(log['log_content'])

        print('LOG:')
        pprint(log)

        print('\nPARSED LOG:')
        pprint(parsed_log)
```

(The complete **test code** and its **output** is can be seen [here](https://gist.github.com/TrongTheAlpaca/50b83ac89980a2c3ede3eb1a3b952bba))

I was wondering how one can learn to interpret the output? If I had to guess, it seems like the output show round-wise log, where some of the tags correspond with specific mahjong tiles and other round-information.
Is there any sources online explaining how I can transcribe the output to more human readable log?

**Comment by TrongTheAlpaca** [comment]
After doing more research, I may have found a sufficient solution for now.
From what I have gathered, it seems like it is possible to parse the output into more human readable format by borrowing some code from  https://github.com/mthrok/tenhou-log-utils.

**Comment by Nihisil** [comment]
Yep, you need some code to parse the log to human readable format. https://github.com/mthrok/tenhou-log-utils looks fine.

**Comment by TrongTheAlpaca** [comment]
Sounds good, this discussion has been sufficient for now. 

Thanks @Nihisil, I appreciate your helpful input!

**Comment by ChitoKim** [comment]
Have you changed the compression to gzip? I continuously got a fail parsing the logs, but as I changed the bz2 to gzip, it worked.

**Comment by Nihisil** [comment]
@ChitoKim yep, it was changed to gzip (to save a bit more space). You can check how to read logs here: https://github.com/MahjongRepository/phoenix-logs/blob/master/validate.py#L48
