### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 27: illegal multibyte sequence

### ISSUE THREAD

**Issue by Majimag111** [MahjongRepository/phoenix-logs#4]
E:\program\phoenix-logs-master>python main.py -a id -y 2022
Latest downloaded archive: scc2022101309.html.gz
Downloading... scc2022101310.html.gz
Preparing the list of games...
Traceback (most recent call last):
  File "E:\program\phoenix-logs-master\main.py", line 69, in <module>
    main()
  File "E:\program\phoenix-logs-master\main.py", line 61, in main
    DownloadGameId(logs_directory, db_file, historical_download, opts.start).process()
  File "E:\program\phoenix-logs-master\download_game_ids.py", line 50, in process
    results = self.process_local_files()
  File "E:\program\phoenix-logs-master\download_game_ids.py", line 184, in process_local_files
    for line in f:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 27: illegal multibyte sequence

Is there any way to solve this?

**Comment by Nihisil** [comment]
What Python version are you using?

**Comment by Majimag111** [comment]
3.9.5

**Comment by Nihisil** [comment]
This version should work fine.

I didn't test it on Windows before, so I think an issue here.

You can try to fix it with changing this line https://github.com/MahjongRepository/phoenix-logs/blob/master/download_game_ids.py#L183 to
```python
with open(os.path.join(self.logs_directory, file_name), 'r', encoding='UTF-8') as f:
```
