### ISSUE TITLE
Do you plan to restrict the download function of mjlog in multiple sessions?

### ISSUE THREAD

**Issue by Apricot-S** [MahjongRepository/phoenix-logs#9]
Hello @Nihisil,

The official account of Tenhou has indicated a policy that download of game records should be limited to one session only.

<https://x.com/tsuno_s/status/1804487739657580636>

Currently, this project supports download of mjlog in multiple sessions.
Do you plan to restrict this function?

Thank you.

**Comment by Nihisil** [comment]
Thanks for reaching out to me. I don't plan to update this repo, so I decided to archive it.

I also added a note about single-thread downloading to the readme, so other developers are aware of it too if they accidentally find this repo: https://github.com/MahjongRepository/phoenix-logs/commit/a38d8f4363528b7b55bce021adf0f15fc202370d
